# -*- coding: utf-8 -*-
"""patternpython.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19DoKWei8TiU-Q_dJbk67Oep6388k8aiQ
"""

#patterns=>
for row in range(0,4):
  for col in range(0,4):
    print("*",end="  ")
  print()

num=7
for row in range(0,num):
  for col in range(0,num):
    print("*",end="  ")
  print()

num=4
for row in range(0,num):
  for col in range(0,row+1):  #(0,1)->(0,2)->(0,3)->(0,4)
    print("*",end="  ")
  print()

num=4
for row in range(0,num):
  for col in range(0,row+1):
    print(col,end="  ")
  print()

num=4
for row in range(0,num):
  for col in range(0,row+1):
    print(row,end="  ")
  print()

num=4
for row in range(0,num):
  for col in range(0,row+1):
    col+=2
    print(col,end="  ")
  print()

num=4
for row in range(0,num):
  x=2
  for col in range(0,row+1):
    print(x,end="  ")
    x+=1
  print()

num=3
x=65
for row in range(0,num):
  for col in range(0,row+1):
    print(x,end="  ")
    x+=1
  print()

num=3
x=65
for row in range(0,num):
  for col in range(0,row+1):
    print(chr(x),end="  ")
    x+=1
  print()

n=4
for i in range(1,n+1):
  for j in range(i,n+1):
    print("*",end="  ")
  print()

n=5
a=10
for i in range(0,n):
  for j in range(i,n):
    print(a,end="  ")
    a+=1
  print()

n=4
for i in range(1,n+1):
  for j in range(i,n+1):
    print(j,end="  ")
  print()

n=4
for i in range(0,n):
  for j in range(i,n):
    print(j+1,end="  ")
  print()

n=5
for i in range(0,n):
  for j in range(i,n):
    if (i+j)%2==0:
      print(1,end="  ")
    else:
      print(0,end="  ")
  print()

#functional approach

n=5
a=1
for i in range(1,n+1):
  for j in range(i,n+1):
    if (i+j)%2==0:
      print(i,end="  ")
    else:
      print(0,end="  ")
      a+=1
  print()

n=4
for i in range(1,n+1):
  for j in range(i,n):
    print(" ",end=" ")
  for k in range(1,i+1):
    print("*",end=' ')
  print()

n=3
for i in range(1,n+1):
  for j in range(i,n+1):
    print("_",end=" ")
  print()

n=5
for i in range(1,n+1):
  for j in range(1,i+1):
    print(" ",end=" ")
  for k in range(i,n+1):
    print("*",end=' ')
  print()

n=4
for i in range(0,n):
  for k in range(0,i):
    print(" ",end=" ")
  for j in range(0,n-i):
    if i==0 or j==0 or j==n-i-2:
      print("*",end=" ")
    else:
      print("",end=" ")
  print()

n=4
a+=1
for i in range(1,n+1):
    for j in range(i,n+1):
      if i==1 or i==j or j==n:
        print(a,end=" ")
      else:
        print(" ",end=" ")
    print()

